routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::prefix('/admin')->group(function () {
    Route::group(['middleware' => ['auth', 'admin']], function () {
        Route::view('/dashboard','backend.index')->name('admin.dashboard');
        Route::resource('/roles', App\Http\Controllers\Backend\RolesController::class);
        Route::resource('/users', App\Http\Controllers\Backend\UsersController::class);
        Route::resource('/settings', App\Http\Controllers\Backend\ConfigsController::class);
        Route::post('users/{id}/update-password', [App\Http\Controllers\Backend\UsersController::class, 'updatePassword'])->name('update.password');
       
        Route::prefix('/master')->group(function () {
            Route::resource('/categories', App\Http\Controllers\Backend\MasterCategoryController::class);
            Route::resource('/country-codes', App\Http\Controllers\Backend\MasterCountryCodeController::class);
            Route::resource('/current-jobs', App\Http\Controllers\Backend\MasterCurrentJobController::class);
            Route::resource('/experiences', App\Http\Controllers\Backend\MasterExperiencesController::class);
            Route::resource('/languages', App\Http\Controllers\Backend\MasterLanguageController::class);
            Route::resource('/levels', App\Http\Controllers\Backend\MasterLevelController::class);
            Route::resource('/locations', App\Http\Controllers\Backend\MasterLocationController::class);
            Route::resource('/nationalities', App\Http\Controllers\Backend\MasterNationalitiesController::class);
            Route::resource('/qualifications', App\Http\Controllers\Backend\MasterQualificationsController::class);
            Route::resource('/salary-ranges', App\Http\Controllers\Backend\MasterSalaryRangeController::class);
            Route::resource('/sectors', App\Http\Controllers\Backend\MasterSectorController::class);
            Route::resource('/types', App\Http\Controllers\Backend\MasterTypeController::class);
        });

        Route::prefix('/settings')->group(function () {
            Route::post('/mail', [App\Http\Controllers\Backend\ConfigsController::class, 'mail'])->name('settings.mail');
        });
    });
});

Route::prefix('jobseeker')->group(function () {
    Route::group(['middleware' => ['auth', 'jobseeker']], function () {
        Route::view('/dashboard','jobseekers.index')->name('jobseeker.dashboard');

        Route::prefix('my-profile')->group(function () {
            //view
            Route::get('/basic-information', [App\Http\Controllers\ProfileJobSeekerController::class, 'basic_information_view'])->name('my-profile.basic-information');   
            Route::get('/introduction', [App\Http\Controllers\ProfileJobSeekerController::class, 'introduction_view'])->name('my-profile.introduction');   
            Route::get('/qualifications', [App\Http\Controllers\ProfileJobSeekerController::class, 'qualifications_view'])->name('my-profile.qualifications');
            Route::get('/work-history', [App\Http\Controllers\ProfileJobSeekerController::class, 'work_history_view'])->name('my-profile.work-history');
            Route::get('/skills', [App\Http\Controllers\ProfileJobSeekerController::class, 'skills_view'])->name('my-profile.skills');
            Route::get('/languages', [App\Http\Controllers\ProfileJobSeekerController::class, 'languages_view'])->name('my-profile.languages');
            Route::get('/resume', [App\Http\Controllers\ProfileJobSeekerController::class, 'resume_view'])->name('my-profile.resume');
            Route::get('/preferences', [App\Http\Controllers\ProfileJobSeekerController::class, 'preferences_view'])->name('my-profile.preferences');
            
            //
            Route::post('/introduction/update/{id}', [App\Http\Controllers\ProfileJobSeekerController::class, 'introduction_post'])->name('my-profile.introduction-post');
            Route::post('/qualifications-post', [App\Http\Controllers\ProfileJobSeekerController::class, 'qualifications_post'])->name('my-profile.qualifications-post');
            Route::delete('/qualifications-{id}', [App\Http\Controllers\ProfileJobSeekerController::class, 'qualifications_delete'])->name('my-profile.qualifications-delete');
            Route::post('/experience-post', [App\Http\Controllers\ProfileJobSeekerController::class, 'work_history_post'])->name('my-profile.experience-post');
            Route::delete('/experience-{id}', [App\Http\Controllers\ProfileJobSeekerController::class, 'work_history_delete'])->name('my-profile.experience-delete');
            Route::post('/skill-post', [App\Http\Controllers\ProfileJobSeekerController::class, 'skill_post'])->name('my-profile.skill-post');
            Route::post('/skill-update/{id}', [App\Http\Controllers\ProfileJobSeekerController::class, 'skill_update'])->name('my-profile.skill-update');
            Route::delete('/skill-{id}', [App\Http\Controllers\ProfileJobSeekerController::class, 'skill_delete'])->name('my-profile.skill-delete');
            Route::post('/language-post', [App\Http\Controllers\ProfileJobSeekerController::class, 'language_post'])->name('my-profile.language-post');
            Route::delete('/language-{id}', [App\Http\Controllers\ProfileJobSeekerController::class, 'language_delete'])->name('my-profile.language-delete');
            Route::get('/work-history-post', [App\Http\Controllers\ProfileJobSeekerController::class, 'work_history_post'])->name('my-profile.work_history_post');
            Route::post('/work-history-store', [App\Http\Controllers\ProfileJobSeekerController::class, 'work_history_post'])->name('my-profile.work-history-store');
            Route::delete('/work-history-{id}', [App\Http\Controllers\ProfileJobSeekerController::class, 'work_history_delete'])->name('my-profile.work-history-delete');
            //id -- ganti auth
            Route::post('/basic-information/update/{id}', [App\Http\Controllers\ProfileJobSeekerController::class, 'basic_information_update'])->name('update.basic-information');
            Route::post('/preferences/update/{id}', [App\Http\Controllers\ProfileJobSeekerController::class, 'preferences_update'])->name('update.preferences');
        });
    });
});

Route::prefix('employer')->group(function () {
    Route::group(['middleware' => ['auth', 'employer']], function () {
        Route::view('/dashboard','employer.index')->name('employer.dashboard');
    });
});
Route::group(['middleware' => ['auth']], function () {
    Route::prefix('security')->group(function () {
        //view
        Route::get('/change-password', [App\Http\Controllers\ProfileJobSeekerController::class, 'change_password_view'])->name('security.change-password'); 
        Route::get('/hide-password', [App\Http\Controllers\ProfileJobSeekerController::class, 'hide_password_view'])->name('security.hide-password');    
        //post
        Route::post('/post-change-password', [App\Http\Controllers\ProfileJobSeekerController::class, 'change_password_post'])->name('security.change-password-post'); 
        Route::post('/post-hide-password', [App\Http\Controllers\ProfileJobSeekerController::class, 'hide_password_post'])->name('security.hide-password-post');    

        
    });
});

resources/views/jobseekers/my-profiles/work-historys/delete.blade.php
<div id="small-dialog-{{$item->id}}" class="zoom-anim-dialog mfp-hide dialog-with-tabs">
	<div class="sign-in-form">
		<div class="sign-in-form">
			<ul class="popup-tabs-nav">
			</ul>
			<div class="popup-tabs-container">
				<!-- Tab -->
				<div class="popup-tab-content" id="tab2">
					
					<!-- Welcome Text -->
					<div class="welcome-text">
						<h3>Leave a Review</h3>
						<span>Rate <a href="#">Peter Valentín</a> for the project <a href="#">Simple Chrome Extension</a> </span>
					</div>
						
					<!-- Form -->
					<form method="post" id="leave-review-form">
	
						<input type="hidden" name="iddelete" id="iddelete">
						<button class="button red full-width button-sliding-icon ripple-effect" type="submit" form="leave-review-form">Leave a Review <i class="icon-material-outline-arrow-right-alt"></i></button>
					</form>
					
					<!-- Button -->
					
	
				</div>
	
			</div>
		</div>
	</div>
</div>

<script>
	
    function remove(id){
		$('#iddelete').val(id);
    }
    function destroyWorkHistory(){
        var id = $('#iddelete').val();
        createOverlay("process...");
        $.ajax({
            type: 'DELETE',
            dataType: 'json',
            url: "/jobseeker/my-profile/work-history-"+id,
			// url: "{{route('users.destroy',["id"])}}",
            data: {
                '_token' : '{{ csrf_token() }}',
                _method: 'DELETE',
                id: id,
            },
            success: function(data){
                gOverlay.hide();
                if(data["status"] == "success") {            
                    toastr.success(data["message"]);
                    setTimeout(function(){ 
                        window.location = "{{ route('my-profile.work_history_post') }}";
                    }, 500);            
                }else {
                    toastr.error(data["message"]);
                }
            },
            error: function(error) {
                alert("Server/network error\r\n" + error);
            }
        });
    }
</script>

resources/views/jobseekers/my-profiles/work-historys/index.blade.php
@extends('layouts.app')
@section('content')
<div class="contents">
    <div class="profile-setting ">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-main">
                        <h4 class="text-capitalize breadcrumb-title">My profile</h4>
                    </div>
                </div>
                @include('layouts.partials._menu_jobseeker')
                <div class="col-xxl-9 col-lg-8 col-sm-7">
                   
                    <div class="mb-50">
                        <div class="edit-profile mt-0">
                            <div class="card">
                                <div class="card-header px-sm-25 px-3">
                                    <div class="edit-profile__title">
                                        <h6>Tell Employers About your Work History</h6>
                                        <span class="fs-13 color-light fw-400">A good qualification is one key factor to get you hired.</span>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="card">
                                        <div class="card-header color-dark fw-500">
                                            <a data-toggle="modal" data-target="#small-dialog" class="btn btn-success popup-with-zoom-anim">Add Qualifications</a>
                                            {{-- <button type="button" class="btn btn-primary btn-sm"  onClick="create()" data-toggle="modal" data-target="#modal-basic">   <i class="las la-plus fs-16"></i>Add</button> --}}
                                        </div>
                                        <div class="card-body p-0">
                                            <div class="table4  p-25 bg-white mb-30">
                                                <div class="table-responsive">
                                                    <table class="table mb-0">
                                                        <thead>
                                                            <tr class="userDatatable-header">
                                                                <th>
                                                                    <span class="userDatatable-title">No</span>
                                                                </th>
                                                                <th>
                                                                    <span class="userDatatable-title">Category</span>
                                                                </th>
                                                                <th>
                                                                    <span class="userDatatable-title">Resume</span>
                                                                </th>
                                                                <th>
                                                                    <span class="userDatatable-title">Employer</span>
                                                                </th>
                                                                <th>
                                                                    <span class="userDatatable-title">Year From</span>
                                                                </th>
                                                                <th>
                                                                    <span class="userDatatable-title">Year To</span>
                                                                </th>
                                                                <th>
                                                                    <span class="userDatatable-title">Duration</span>
                                                                </th>
                                                                <th>
                                                                    <span class="userDatatable-title">Job Title</span>
                                                                </th>
                                                                <th>
                                                                    <span class="userDatatable-title">Refree Name</span>
                                                                </th>
                                                                <th>
                                                                    <span class="userDatatable-title">Refree Contact</span>
                                                                </th>
                                                                <th>
                                                                    <span class="userDatatable-title">Work Summary</span>
                                                                </th>
                                                                <th>
                                                                    <span class="userDatatable-title">Responsibilities</span>
                                                                </th>
                                                                <th>
                                                                    <span class="userDatatable-title">Action</span>
                                                                </th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            @foreach ($workHistory as $item)
                                                            <tr>
                                                                <td>
                                                                    <div class="userDatatable-content">
                                                                        {{ $loop->iteration }}
                                                                    </div>
                                                                </td>
                                                                <td>
                                                                    <div class="userDatatable-content">
                                                                        {{$item->category_id}}
                                                                        
                                                                    </div>
                                                                </td>
                                                                <td>
                                                                    <div class="userDatatable-content">
                                                                        {{$item->resume_id}}
                                                                    </div>
                                                                </td>
                                                                <td>
                                                                    <div class="userDatatable-content">
                                                                        {{$item->employer}}
                                                                    </div>
                                                                </td>
                                                                <td>
                                                                    <div class="userDatatable-content">
                                                                        {{$item->year_from}}
                                                                    </div>
                                                                </td>
                                                                <td>
                                                                    <div class="userDatatable-content">
                                                                        {{$item->year_to}}
                                                                    </div>
                                                                </td>
                                                                <td>
                                                                    <div class="userDatatable-content">
                                                                        {{$item->duration}}
                                                                    </div>
                                                                </td>
                                                                <td>
                                                                    <div class="userDatatable-content">
                                                                        {{$item->job_title}}
                                                                    </div>
                                                                </td>
                                                                <td>
                                                                    <div class="userDatatable-content">
                                                                        {{$item->referee_name}}
                                                                    </div>
                                                                </td>
                                                                <td>
                                                                    <div class="userDatatable-content">
                                                                        {{$item->referee_contact}}
                                                                    </div>
                                                                </td>
                                                                <td>
                                                                    <div class="userDatatable-content">
                                                                        {{$item->work_summary}}
                                                                    </div>
                                                                </td>
                                                                <td>
                                                                    <div class="userDatatable-content">
                                                                        {{$item->responsibilities}}
                                                                    </div>
                                                                </td>
                                                                <td>
                                                                    {{-- @can ('users-delete')
                                                                    
                                                                        {!! Form::open([
                                                                            'method'=>'DELETE',
                                                                            'route' => ['survey.destroy', $item->id],
                                                                            'style' => 'display:inline'
                                                                        ]) !!}
                                                                        {!! Form::button('<i class="fi fi-trash"></i>', array(
                                                                                    'type' => 'submit',
                                                                                    
                                                                                    'title' => 'Delete Survey',
                                                                                    'onclick'=>'return confirm("Confirm delete?")'
                                                                            )) !!}
                                                                        {!! Form::close() !!}
                                                                        
                                                                    @endcan --}}
                                                                </td>
                                                            </tr>
                                                            @endforeach
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                            
                </div>
            </div>
        </div>
    </div>
</div>


@include('jobseekers.my-profiles.work-historys.modal')


@endsection

resources/views/jobseekers/my-profiles/work-historys/modal.blade.php
<div id="small-dialog" class="zoom-anim-dialog mfp-hide dialog-with-tabs">

	<!--Tabs -->
	<div class="sign-in-form">

		<ul class="popup-tabs-nav">
			<li><a href="#tab1">Add Qualifications</a></li>
		</ul>

		<div class="popup-tabs-container">

			<!-- Tab -->
			<div class="popup-tab-content" id="tab">

				<form id="terms">
                
                    <div class="col">
                        <div class="row">

                            <div class="col-xl-12">
                                <div class="submit-field">
                                    <h5>Institute / School</h5>
                                    <input type="text" class="with-border" name="institute" id="institute">
                                </div>
                            </div>
                            <div class="col-xl-6">
                                <div class="submit-field">
                                    <h5>Completed on</h5>
                                    <input type="text" class="with-border" name="year" id="year">
                                </div>
                            </div>
                            <div class="col-xl-6">
                                <div class="submit-field">
                                    <h5>Level</h5>
                                    {{-- @if(count($list_levels) > 0) --}}
                                        <select class="selectpicker with-border" onchange="levels()"data-size="7"  id="level_id" title="Select One">
                                            {{-- @foreach($list_levels as $id => $value) --}}
                                                {{-- <option value="{{ $value }}" {{ $value }}>{{ $value->name }}</option> --}}
                                            {{-- @endforeach --}}
                                        </select>
                                    {{-- @else --}}
                                        <p>There are no Level options, make it first ...!</p>
                                    {{-- @endif --}}
                                </div>
                            </div>
                            <div class="col" id="grade" style="display: none;">
                                <h5>Mention your subjects and grade results</h5>
                               <div class="row">
                                    <table  id="dynamic_field">  
                                        <tr>  
                                            <td data-label="Column 1">
                                                <input type="text" name="subject[]" placeholder="Enter Subject" class="with-border subject" />
                                            </td> 
                                            <td data-label="Column 2">
                                                <select class="result with-border" name="result[]" title="More">
                                                    <option value="1">A*</option>
                                                    <option value="2">A</option>
                                                    <option value="3">B</option>
                                                    <option value="4">C</option>
                                                    <option value="5">D</option>
                                                    <option value="6">E</option>
                                                    <option value="7">F</option>
                                                    <option value="8">G</option>
                                                    <option value="9">U</option>
                                                </select>
                                            </td> 
                                            <td data-label="Column 3"><button type="button" name="add" id="add" class="button1 red ripple-effect ico"><i class="icon-material-outline-add"></i></button></td>  
                                        </tr>  
                                    </table> 
                                </div> 
                            </div>

                            <div class="col-xl-12">
                                <div class="submit-field">
                                    <h5>Course Name</h5>
                                    <input type="text" class="with-border" name="course_name" id="course_name">
                                </div>
                            </div>

                        </div>
                    </div>
				</form>

				<!-- Button -->
				<button onclick="storeQualification()" type="button" class="margin-top-15 button full-width button-sliding-icon ripple-effect" type="submit" form="terms">Accept <i class="icon-material-outline-arrow-right-alt"></i></button>

			</div>

		</div>
	</div>
</div>
<!-- Bid Acceptance Popup / End -->

<script>

    function storeQualification() {
            var institute = $('#institute').val();
            var year = $('#year').val();
            var level_id = $('#level_id').val();
            var course_name = $('#course_name').val();
            var count = 1;
            var error = '';
            var subject = new Array();
                $('.subject').each(function() {
                
                    if($(this).val() == '')
                    {
                        error += "<p>Pilih subject dibaris ke-"+count+"</p>";
                        
                    }
                    count = count + 1;
                    subject.push($(this).val());
            });

            var result = new Array();
                $('.result').each(function() {
                
                    if($(this).val() == '')
                    {
                        error += "<p>Masukan result dibaris ke-"+count+"</p>";
                    
                    }
                    count = count + 1;
                    result.push($(this).val());
            });
            createOverlay("Proses...");

            $.ajax({
                type : "POST",
                url: "{!! route('my-profile.work-history-store') !!}",
                data: {
                    '_token' : '{{ csrf_token() }}',
                    'institute' : institute,
                    'year' : year,
                    'level_id' : level_id,
                    'course_name' : course_name,
                    'subject' : subject,
                    'result' : result,
                },
                success: function(data){
                    gOverlay.hide();
                    if(data["status"] == "success") {            
                        toastr.success(data["message"]);
                        setTimeout(function(){ 
                            window.location = "{{ route('my-profile.work_history_post') }}";
                        }, 500); 
                    }else {
                        toastr.error(data["message"]);
                    }
                },
                error: function(error) {
                    alert("Server/network error\r\n" + error);
                }
            });
        }

        function levels(){

            var level_id = $('#level_id').val();
            const obj = JSON.parse(level_id);
            if (obj.status_grade==1) {
                $("#grade").show();
            }else{
                $("#grade").hide();
            }
        }

        $(document).ready(function(){      
        var i=1;  
        $('#add').click(function(){  
            i++;  
            $('#dynamic_field').append('<tr id="row'+i+'" class="dynamic-added"><td><input type="text" name="name[]" placeholder="Enter Subject" class="with-border subject" /></td><td><select  name="result[]" title="Select One" class="result with-border"><option value="1">A*</option><option value="2">A</option><option value="3">B</option><option value="4">C</option><option value="5">D</option><option value="6">E</option><option value="7">F</option><option value="8">G</option><option value="9">U</option></select></td><td><button type="button" name="remove" id="'+i+'" class="button2 red ripple-effect ico btn_remove"><i class="icon-feather-trash-2"></i></button></td></tr>');  
            });  


        $(document).on('click', '.btn_remove', function(){  
            var button_id = $(this).attr("id");   
            $('#row'+button_id+'').remove();  
        });  
        }); 

    
</script>